language: node_js
node_js: "8"

cache:
  directories:
  - node_modules

script:
  - npm run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  target_branch: gh-pages
  branch: travis-ci-test